cpe-kmutt-student/comcamp34

src/components/SelectInput.tsx, src/pages/RegistrationPage.tsx
=> feat(select-input)

src/components/Inputbox.tsx
=> add-generic-inputbox

src/components/FileUploaderComponent.tsx, src/pages/RegistrationPage.tsx
ใส่ Form สำหรับอัปโหลดและปุ่มกดอัปโหลด
เมื่ออัปโหลดแล้วฟอร์มจะหายไป ปุ่มลบไฟล์จะเข้ามาแทนที่
* note (วิธีการอัปโหลดสามารถบอกได้ว่าอยากได้แบบไหน ตอนนี้เป็นปุ่มอัปโหลดกับฟอร์ม 1:1)
=> feat(image-file-input-box)

src/components/Button.tsx, src/pages/RegistrationPage.tsx
=> feat(generic-button)

src/components/GpaxInput.tsx
=> add gpax inputbox

index.html, src/components/registrationForm/ConsentForm.tsx, src/pages/RegistrationPage.tsx
Consent form in registration page 
add a little tailwinds styling for see overview of this task
=> feat(consent-form)

src/components/registrationForm/ConsentForm.tsx
=> CHANGE : Data Policy according Registration Team

captain-definition
Add captain-definition file for caprover docker deployment
=> Feat(preview)

src/components/registrationForm/PersonalInfoForm.tsx, src/pages/RegistrationPage.tsx
=> build(test-deploy)

public/assets/svg/LeftArrow.svg, public/assets/svg/RightArrow.svg, src/components/registrationForm/ConsentForm.tsx, src/pages/RegistrationPage.tsx
=> ✨feat: Step Form

src/components/FileUploaderComponent.tsx, src/components/registrationForm/UploadFilesForm.tsx, src/pages/RegistrationPage.tsx
=> FIX : Styling file uploads data

src/components/homePage/ContactSection.tsx
Add href to Social Media and Telephone Number.
Fix overflow
=> Fix(contact section)

src/components/registrationForm/EducationForm.tsx, src/components/registrationForm/InterestForm.tsx
=> Responsive

src/components/FileUploaderComponent.tsx, src/components/registrationForm/UploadFilesForm.tsx
=> HOTFIX : Failed to load resource on server

index.html
Reverts cpe-kmutt-student/comcamp34#102
=> Revert "FEAT Add cloudflare analytic script to index.html"

src/components/homePage/ContactSection.tsx
=> HOTFIX svg width and height from auto to 100%

src/components/DropdownSearch.tsx, src/components/registrationForm/EducationForm.tsx, src/components/registrationForm/InterestForm.tsx, src/components/registrationForm/ParentDataForm.tsx, src/components/registrationForm/PersonalInfoForm.tsx, src/components/registrationForm/QuestionFormpage1.tsx, src/components/registrationForm/QuestionFormpage2.tsx, src/components/registrationForm/UploadFilesForm.tsx, src/index.css, src/pages/RegistrationPage.tsx, src/types/RegistrationType.ts
Co-authored-by: Panurut Sirinapaisan <9.panuruj13@gmail.com>
Co-authored-by: SSSBoOm <boom1909chanapat@gmail.com>
=> :gear:refactor: Rewrite Interface Type

.env.example, package-lock.json, package.json, public/assets/regisPage/profileIcon.svg, src/components/Checkboxinput.tsx, src/components/DropdownSearch.tsx, src/components/EmailInput.tsx, src/components/GpaxInput.tsx, src/components/Inputbox.tsx, src/components/SelectInput.tsx, src/components/Telephoneinputbox.tsx, src/components/Textareainput.tsx, src/components/homePage/FAQSection.tsx, src/components/homePage/LandingSection.tsx, src/components/homePage/Navbar.tsx, src/components/registrationForm/ConsentForm.tsx, src/components/registrationForm/InterestForm.tsx, src/components/registrationForm/ParentDataForm.tsx, src/components/registrationForm/PersonalInfoForm.tsx, src/components/registrationForm/QuestionFormpage2.tsx, src/lib/CustomSwal.ts, src/lib/Fetch.ts, src/main.tsx, src/pages/LoginPage.tsx, src/pages/RegistrationPage.tsx, src/types/RegistrationType.ts
Sync Form Sed leaw Sasssssssssssssss
Co-authored-by: SSSBoOm <boom1909chanapat@gmail.com>
Co-authored-by: Panurut Sirinapaisan <9.panuruj13@gmail.com>
=> ✨feat: Sync Form

package-lock.json, package.json, src/components/homePage/AboutSection.tsx, src/components/homePage/ConditionsSection.tsx, src/components/homePage/ContactSection.tsx, src/components/homePage/FAQSection.tsx, src/components/homePage/Footer.tsx, src/components/homePage/LearningSection.tsx, src/components/homePage/Navbar.tsx, src/components/homePage/SponsorSection.tsx, src/components/homePage/TimelineSection.tsx, src/pages/FrontPage.tsx
=> FEAT : Navbar scrolling & Scroll to top Button

src/App.tsx, src/components/homePage/LandingSection.tsx, src/components/homePage/Navbar.tsx, src/lib/CustomSwal.ts
REMOVE :  /registraion Routes
ADD : Sweetalert2 popup for announce about "ขออภัย ไม่อยู่ในช่วงเวลารับสมัคร " when click registration button
=> :ambulance:HOTFIX : Closed Registration

src/components/EmailInput.tsx, src/components/GpaxInput.tsx, src/components/Telephoneinputbox.tsx, src/pages/RegistrationPage.tsx, src/utils/validate.ts
=> :adhesive_bandage:FIX : Gpax input one floating point 

src/components/homePage/AboutSection.tsx, src/components/homePage/ConditionsSection.tsx, src/components/homePage/FAQSection.tsx, src/components/homePage/LearningSection.tsx, src/components/homePage/Navbar.tsx, src/components/homePage/TimelineSection.tsx
=> :adhesive_bandage:FIX : padding heading text

src/components/registrationForm/ConsentForm.tsx, src/components/registrationForm/UploadFilesForm.tsx, src/lib/Fetch.ts, src/pages/RegistrationPage.tsx, src/utils/validate.ts
Co-authored-by: SSSBoOm <boom1909chanapat@gmail.com>
=> ✨feat: Submit Form

src/components/FileUploaderComponent.tsx, src/components/registrationForm/UploadFilesForm.tsx, src/pages/RegistrationPage.tsx
Co-authored-by: Thanaphol <Thanaphol47825@users.noreply.github.com>
Co-authored-by: Chaiyapat Oam <ChaiyapatOam@users.noreply.github.com>
Co-authored-by: Panurut Sirinapaisan <9.panuruj13@gmail.com>
=> Co-authored-by: SSSBoOm <boom1909chanapat@gmail.com>

.env.example, package-lock.json, package.json, src/gaEvents.ts, src/main.tsx, src/pages/LoginPage.tsx
Caution ⚠️ 
- Please add VITE_GA to .env on production server before merging.
=> feat: google analytics

src/components/ConfirmmationForm/ExaminationInfo.tsx, src/lib/CustomSwal.ts, src/pages/ResultPage.tsx
=> :sparkles:ADD : Examination Info (page 2)

src/components/ConfirmmationForm/ConfirmForm.tsx, src/components/FileUploaderComponent.tsx, src/components/registrationForm/DropdownData/shirtsize_data.json, src/lib/CustomSwal.ts, src/pages/ResultPage.tsx, src/types/ConfirmationType.tsx
Features:
- Shirt size select input
- when selected "สละสิทธิ์" will disabled all input components
- when selected "สละสิทธิ์" when press next page will show Confirmation Popup that you will waive in this camp by your selected
- Image preview when upload image
Image Attachments:
=> :sparkles:ADD : Confirmation page features
